// SPDX-License-Identifier: Apache-2.0

#pragma once

/**
 * @file
 * @brief Symbol visibility for the shared build.
 *
 * Hand-written rather than generated by CMake's generate_export_header(), because this project
 * builds a shared *and* a static library from the same sources and that generator keys its
 * "am I being built?" macro off a single target name.
 *
 * Three cases:
 *  - building the shared library      - EUCLID_CDK_BUILDING_SHARED is defined, so export;
 *  - consuming the shared library     - neither macro is defined, so import (Windows only);
 *  - building or consuming the static - EUCLID_CDK_STATIC_DEFINE is defined, so neither. The static
 *    target carries it as a PUBLIC compile definition, so a consumer gets it from CMake.
 */

#if defined(EUCLID_CDK_STATIC_DEFINE)
#define EUCLID_CDK_API
#elif defined(_WIN32)
#if defined(EUCLID_CDK_BUILDING_SHARED)
#define EUCLID_CDK_API __declspec(dllexport)
#else
#define EUCLID_CDK_API __declspec(dllimport)
#endif
#else
#define EUCLID_CDK_API __attribute__((visibility("default")))
#endif
